################################################################################
# Automatically-generated file. Do not edit!
# Toolchain: GNU Tools for STM32 (12.3.rel1)
################################################################################

ELF_SRCS := 
OBJ_SRCS := 
S_SRCS := 
C_SRCS := 
S_UPPER_SRCS := 
O_SRCS := 
CYCLO_FILES := 
SIZE_OUTPUT := 
OBJDUMP_LIST := 
SU_FILES := 
EXECUTABLES := 
OBJS := 
MAP_FILES := 
S_DEPS := 
S_UPPER_DEPS := 
C_DEPS := 

# Every subdirectory with source files must be described here
SUBDIRS := \
Common/Src \
Core/Src \
Core/Startup \
Drivers/BSP/Components/mt48lc4m32b2 \
Drivers/STM32H7xx_HAL_Driver \
Gas_Scheduler \
Open_Src/lvgl/demos/benchmark/assets \
Open_Src/lvgl/demos/benchmark \
Open_Src/lvgl/demos/keypad_encoder \
Open_Src/lvgl/demos/music/assets \
Open_Src/lvgl/demos/music \
Open_Src/lvgl/demos/stress/assets \
Open_Src/lvgl/demos/stress \
Open_Src/lvgl/demos/widgets/assets \
Open_Src/lvgl/demos/widgets \
Open_Src/lvgl/examples/anim \
Open_Src/lvgl/examples/assets \
Open_Src/lvgl/examples/event \
Open_Src/lvgl/examples/get_started \
Open_Src/lvgl/examples/layouts/flex \
Open_Src/lvgl/examples/layouts/grid \
Open_Src/lvgl/examples/libs/bmp \
Open_Src/lvgl/examples/libs/ffmpeg \
Open_Src/lvgl/examples/libs/freetype \
Open_Src/lvgl/examples/libs/gif \
Open_Src/lvgl/examples/libs/png \
Open_Src/lvgl/examples/libs/qrcode \
Open_Src/lvgl/examples/libs/rlottie \
Open_Src/lvgl/examples/libs/sjpg \
Open_Src/lvgl/examples/others/monkey \
Open_Src/lvgl/examples/others/snapshot \
Open_Src/lvgl/examples/porting \
Open_Src/lvgl/examples/scroll \
Open_Src/lvgl/examples/styles \
Open_Src/lvgl/examples/widgets/animimg \
Open_Src/lvgl/examples/widgets/arc \
Open_Src/lvgl/examples/widgets/bar \
Open_Src/lvgl/examples/widgets/btn \
Open_Src/lvgl/examples/widgets/btnmatrix \
Open_Src/lvgl/examples/widgets/calendar \
Open_Src/lvgl/examples/widgets/canvas \
Open_Src/lvgl/examples/widgets/chart \
Open_Src/lvgl/examples/widgets/checkbox \
Open_Src/lvgl/examples/widgets/colorwheel \
Open_Src/lvgl/examples/widgets/dropdown \
Open_Src/lvgl/examples/widgets/img \
Open_Src/lvgl/examples/widgets/imgbtn \
Open_Src/lvgl/examples/widgets/keyboard \
Open_Src/lvgl/examples/widgets/label \
Open_Src/lvgl/examples/widgets/led \
Open_Src/lvgl/examples/widgets/line \
Open_Src/lvgl/examples/widgets/list \
Open_Src/lvgl/examples/widgets/menu \
Open_Src/lvgl/examples/widgets/meter \
Open_Src/lvgl/examples/widgets/msgbox \
Open_Src/lvgl/examples/widgets/obj \
Open_Src/lvgl/examples/widgets/roller \
Open_Src/lvgl/examples/widgets/slider \
Open_Src/lvgl/examples/widgets/span \
Open_Src/lvgl/examples/widgets/spinbox \
Open_Src/lvgl/examples/widgets/spinner \
Open_Src/lvgl/examples/widgets/switch \
Open_Src/lvgl/examples/widgets/table \
Open_Src/lvgl/examples/widgets/tabview \
Open_Src/lvgl/examples/widgets/textarea \
Open_Src/lvgl/examples/widgets/tileview \
Open_Src/lvgl/examples/widgets/win \
Open_Src/lvgl/rt-thread \
Open_Src/lvgl/src/core \
Open_Src/lvgl/src/draw \
Open_Src/lvgl/src/draw/nxp_pxp \
Open_Src/lvgl/src/draw/nxp_vglite \
Open_Src/lvgl/src/draw/sdl \
Open_Src/lvgl/src/draw/stm32_dma2d \
Open_Src/lvgl/src/draw/sw \
Open_Src/lvgl/src/extra/layouts/flex \
Open_Src/lvgl/src/extra/layouts/grid \
Open_Src/lvgl/src/extra/libs/bmp \
Open_Src/lvgl/src/extra/libs/ffmpeg \
Open_Src/lvgl/src/extra/libs/freetype \
Open_Src/lvgl/src/extra/libs/fsdrv \
Open_Src/lvgl/src/extra/libs/gif \
Open_Src/lvgl/src/extra/libs/png \
Open_Src/lvgl/src/extra/libs/qrcode \
Open_Src/lvgl/src/extra/libs/rlottie \
Open_Src/lvgl/src/extra/libs/sjpg \
Open_Src/lvgl/src/extra \
Open_Src/lvgl/src/extra/others/monkey \
Open_Src/lvgl/src/extra/others/snapshot \
Open_Src/lvgl/src/extra/themes/basic \
Open_Src/lvgl/src/extra/themes/default \
Open_Src/lvgl/src/extra/themes/mono \
Open_Src/lvgl/src/extra/widgets/animimg \
Open_Src/lvgl/src/extra/widgets/calendar \
Open_Src/lvgl/src/extra/widgets/chart \
Open_Src/lvgl/src/extra/widgets/colorwheel \
Open_Src/lvgl/src/extra/widgets/imgbtn \
Open_Src/lvgl/src/extra/widgets/keyboard \
Open_Src/lvgl/src/extra/widgets/led \
Open_Src/lvgl/src/extra/widgets/list \
Open_Src/lvgl/src/extra/widgets/menu \
Open_Src/lvgl/src/extra/widgets/meter \
Open_Src/lvgl/src/extra/widgets/msgbox \
Open_Src/lvgl/src/extra/widgets/span \
Open_Src/lvgl/src/extra/widgets/spinbox \
Open_Src/lvgl/src/extra/widgets/spinner \
Open_Src/lvgl/src/extra/widgets/tabview \
Open_Src/lvgl/src/extra/widgets/tileview \
Open_Src/lvgl/src/extra/widgets/win \
Open_Src/lvgl/src/font \
Open_Src/lvgl/src/hal \
Open_Src/lvgl/src/misc \
Open_Src/lvgl/src/widgets \
Open_Src/lvgl/tests/src \
Open_Src/lvgl/tests/src/test_cases \
Open_Src/lvgl/tests/src/test_fonts \
Open_Src/lvgl/tests/unity \

